// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// q8
NumericVector q8(NumericVector x, NumericVector probs);
RcppExport SEXP mqr_q8(SEXP xSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    __result = Rcpp::wrap(q8(x, probs));
    return __result;
END_RCPP
}
// mqC
NumericMatrix mqC(NumericVector y, NumericVector q, IntegerVector l, NumericVector d);
RcppExport SEXP mqr_mqC(SEXP ySEXP, SEXP qSEXP, SEXP lSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type l(lSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    __result = Rcpp::wrap(mqC(y, q, l, d));
    return __result;
END_RCPP
}
